# Form implementation generated from reading ui file 'widget_addsemester.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddSemester(object):
    def setupUi(self, AddSemester):
        AddSemester.setObjectName("AddSemester")
        AddSemester.resize(356, 139)
        AddSemester.setMinimumSize(QtCore.QSize(356, 139))
        AddSemester.setMaximumSize(QtCore.QSize(405, 180))
        AddSemester.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(AddSemester)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=AddSemester)
        self.frame_2.setStyleSheet("background-color: rgb(6, 12, 10);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_SemesterNumber = QtWidgets.QLabel(parent=self.frame_2)
        self.label_SemesterNumber.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_SemesterNumber.setObjectName("label_SemesterNumber")
        self.verticalLayout_2.addWidget(self.label_SemesterNumber)
        self.label_StartDate = QtWidgets.QLabel(parent=self.frame_2)
        self.label_StartDate.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_StartDate.setObjectName("label_StartDate")
        self.verticalLayout_2.addWidget(self.label_StartDate)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(parent=AddSemester)
        self.frame.setStyleSheet("background-color: rgb(6, 12, 10);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_SemesterNumber = QtWidgets.QComboBox(parent=self.frame)
        self.comboBox_SemesterNumber.setStyleSheet("background-color: rgb(192, 191, 188);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_SemesterNumber.setObjectName("comboBox_SemesterNumber")
        self.verticalLayout.addWidget(self.comboBox_SemesterNumber)
        self.dateEdit_StartDate = QtWidgets.QDateEdit(parent=self.frame)
        self.dateEdit_StartDate.setStyleSheet("background-color: rgb(246, 245, 244);\n"
"color: rgb(0, 0, 0);")
        self.dateEdit_StartDate.setObjectName("dateEdit_StartDate")
        self.verticalLayout.addWidget(self.dateEdit_StartDate)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AddSemester)
        self.buttonBox.setStyleSheet("background-color: rgb(246, 245, 244);\n"
"color: rgb(0, 0, 0);")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(AddSemester)
        QtCore.QMetaObject.connectSlotsByName(AddSemester)

    def retranslateUi(self, AddSemester):
        _translate = QtCore.QCoreApplication.translate
        AddSemester.setWindowTitle(_translate("AddSemester", "Add Semester"))
        self.label_SemesterNumber.setText(_translate("AddSemester", "Semester Number"))
        self.label_StartDate.setText(_translate("AddSemester", "Start Date"))
