# Form implementation generated from reading ui file 'widget_addcourse.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddCourse(object):
    def setupUi(self, AddCourse):
        AddCourse.setObjectName("AddCourse")
        AddCourse.resize(307, 148)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddCourse.sizePolicy().hasHeightForWidth())
        AddCourse.setSizePolicy(sizePolicy)
        AddCourse.setMinimumSize(QtCore.QSize(307, 148))
        AddCourse.setMaximumSize(QtCore.QSize(405, 180))
        AddCourse.setStyleSheet("background-color: rgb(6, 12, 10);")
        self.verticalLayout = QtWidgets.QVBoxLayout(AddCourse)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DataInput = QtWidgets.QFormLayout()
        self.DataInput.setObjectName("DataInput")
        self.label_CourseName = QtWidgets.QLabel(parent=AddCourse)
        self.label_CourseName.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_CourseName.setObjectName("label_CourseName")
        self.DataInput.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_CourseName)
        self.comboBox_CourseName = QtWidgets.QComboBox(parent=AddCourse)
        self.comboBox_CourseName.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.comboBox_CourseName.setObjectName("comboBox_CourseName")
        self.DataInput.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox_CourseName)
        self.label_ECTSPoints = QtWidgets.QLabel(parent=AddCourse)
        self.label_ECTSPoints.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_ECTSPoints.setObjectName("label_ECTSPoints")
        self.DataInput.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_ECTSPoints)
        self.lineEdit_ECTSPoints = QtWidgets.QLineEdit(parent=AddCourse)
        self.lineEdit_ECTSPoints.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.lineEdit_ECTSPoints.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_ECTSPoints.setObjectName("lineEdit_ECTSPoints")
        self.DataInput.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_ECTSPoints)
        self.label_ExamType = QtWidgets.QLabel(parent=AddCourse)
        self.label_ExamType.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_ExamType.setObjectName("label_ExamType")
        self.DataInput.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_ExamType)
        self.comboBox_ExamType = QtWidgets.QComboBox(parent=AddCourse)
        self.comboBox_ExamType.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.comboBox_ExamType.setObjectName("comboBox_ExamType")
        self.DataInput.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox_ExamType)
        self.verticalLayout.addLayout(self.DataInput)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AddCourse)
        self.buttonBox.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(AddCourse)
        QtCore.QMetaObject.connectSlotsByName(AddCourse)

    def retranslateUi(self, AddCourse):
        _translate = QtCore.QCoreApplication.translate
        AddCourse.setWindowTitle(_translate("AddCourse", "Add Course"))
        self.label_CourseName.setText(_translate("AddCourse", "Course Name"))
        self.label_ECTSPoints.setText(_translate("AddCourse", "ECTS Points"))
        self.lineEdit_ECTSPoints.setText(_translate("AddCourse", "5"))
        self.lineEdit_ECTSPoints.setPlaceholderText(_translate("AddCourse", "5"))
        self.label_ExamType.setText(_translate("AddCourse", "Exam Type"))
