# Form implementation generated from reading ui file 'widget_addsemester.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddSemester(object):
    def setupUi(self, AddSemester):
        AddSemester.setObjectName("AddSemester")
        AddSemester.resize(356, 139)
        AddSemester.setMinimumSize(QtCore.QSize(356, 139))
        AddSemester.setMaximumSize(QtCore.QSize(405, 180))
        AddSemester.setStyleSheet("background-color: rgb(6, 12, 10);")
        self.verticalLayout = QtWidgets.QVBoxLayout(AddSemester)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DataInput = QtWidgets.QFormLayout()
        self.DataInput.setObjectName("DataInput")
        self.label_SemesterNumber = QtWidgets.QLabel(parent=AddSemester)
        self.label_SemesterNumber.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_SemesterNumber.setObjectName("label_SemesterNumber")
        self.DataInput.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_SemesterNumber)
        self.comboBox_SemesterNumber = QtWidgets.QComboBox(parent=AddSemester)
        self.comboBox_SemesterNumber.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.comboBox_SemesterNumber.setObjectName("comboBox_SemesterNumber")
        self.DataInput.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox_SemesterNumber)
        self.label_StartDate = QtWidgets.QLabel(parent=AddSemester)
        self.label_StartDate.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_StartDate.setObjectName("label_StartDate")
        self.DataInput.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_StartDate)
        self.dateEdit_StartDate = QtWidgets.QDateEdit(parent=AddSemester)
        self.dateEdit_StartDate.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.dateEdit_StartDate.setObjectName("dateEdit_StartDate")
        self.DataInput.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateEdit_StartDate)
        self.verticalLayout.addLayout(self.DataInput)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AddSemester)
        self.buttonBox.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(AddSemester)
        QtCore.QMetaObject.connectSlotsByName(AddSemester)

    def retranslateUi(self, AddSemester):
        _translate = QtCore.QCoreApplication.translate
        AddSemester.setWindowTitle(_translate("AddSemester", "Add Semester"))
        self.label_SemesterNumber.setText(_translate("AddSemester", "Semester Number"))
        self.label_StartDate.setText(_translate("AddSemester", "Start Date"))
