# Form implementation generated from reading ui file 'widget_addgrade.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddGrade(object):
    def setupUi(self, AddGrade):
        AddGrade.setObjectName("AddGrade")
        AddGrade.resize(233, 180)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddGrade.sizePolicy().hasHeightForWidth())
        AddGrade.setSizePolicy(sizePolicy)
        AddGrade.setMinimumSize(QtCore.QSize(233, 180))
        AddGrade.setMaximumSize(QtCore.QSize(405, 180))
        AddGrade.setStyleSheet("background-color: rgb(6, 12, 10);")
        self.verticalLayout = QtWidgets.QVBoxLayout(AddGrade)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DataInput = QtWidgets.QFormLayout()
        self.DataInput.setObjectName("DataInput")
        self.label_Modul = QtWidgets.QLabel(parent=AddGrade)
        self.label_Modul.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_Modul.setObjectName("label_Modul")
        self.DataInput.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_Modul)
        self.comboBox_Modul = QtWidgets.QComboBox(parent=AddGrade)
        self.comboBox_Modul.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.comboBox_Modul.setObjectName("comboBox_Modul")
        self.DataInput.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox_Modul)
        self.label_Passed = QtWidgets.QLabel(parent=AddGrade)
        self.label_Passed.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_Passed.setObjectName("label_Passed")
        self.DataInput.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_Passed)
        self.label_Grade = QtWidgets.QLabel(parent=AddGrade)
        self.label_Grade.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_Grade.setObjectName("label_Grade")
        self.DataInput.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_Grade)
        self.lineEdit_Grade = QtWidgets.QLineEdit(parent=AddGrade)
        self.lineEdit_Grade.setStyleSheet("background-color: rgb(246, 245, 244);")
        self.lineEdit_Grade.setObjectName("lineEdit_Grade")
        self.DataInput.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_Grade)
        spacerItem = QtWidgets.QSpacerItem(81, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.DataInput.setItem(3, QtWidgets.QFormLayout.ItemRole.LabelRole, spacerItem)
        self.comboBox_Passed = QtWidgets.QComboBox(parent=AddGrade)
        self.comboBox_Passed.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.comboBox_Passed.setObjectName("comboBox_Passed")
        self.DataInput.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox_Passed)
        self.verticalLayout.addLayout(self.DataInput)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AddGrade)
        self.buttonBox.setStyleSheet("background-color: rgb(246, 245, 244);")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(AddGrade)
        QtCore.QMetaObject.connectSlotsByName(AddGrade)

    def retranslateUi(self, AddGrade):
        _translate = QtCore.QCoreApplication.translate
        AddGrade.setWindowTitle(_translate("AddGrade", "Add Grade"))
        self.label_Modul.setText(_translate("AddGrade", "Modul"))
        self.label_Passed.setText(_translate("AddGrade", "Passed"))
        self.label_Grade.setText(_translate("AddGrade", "Grade"))
