# Form implementation generated from reading ui file 'widget_adduserdata.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NewUserData(object):
    def setupUi(self, NewUserData):
        NewUserData.setObjectName("NewUserData")
        NewUserData.resize(405, 180)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NewUserData.sizePolicy().hasHeightForWidth())
        NewUserData.setSizePolicy(sizePolicy)
        NewUserData.setMinimumSize(QtCore.QSize(405, 180))
        NewUserData.setMaximumSize(QtCore.QSize(405, 180))
        NewUserData.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        NewUserData.setWindowOpacity(1.0)
        NewUserData.setStyleSheet("background-color: rgb(6, 12, 10);")
        self.verticalLayout = QtWidgets.QVBoxLayout(NewUserData)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DataInput = QtWidgets.QFormLayout()
        self.DataInput.setObjectName("DataInput")
        self.label_University = QtWidgets.QLabel(parent=NewUserData)
        self.label_University.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_University.setObjectName("label_University")
        self.DataInput.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_University)
        self.comboBox_University = QtWidgets.QComboBox(parent=NewUserData)
        self.comboBox_University.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.comboBox_University.setObjectName("comboBox_University")
        self.DataInput.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox_University)
        self.label_StudentName = QtWidgets.QLabel(parent=NewUserData)
        self.label_StudentName.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_StudentName.setObjectName("label_StudentName")
        self.DataInput.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_StudentName)
        self.lineEdit_StudentName = QtWidgets.QLineEdit(parent=NewUserData)
        self.lineEdit_StudentName.setStyleSheet("background-color: rgb(246, 245, 244);")
        self.lineEdit_StudentName.setText("")
        self.lineEdit_StudentName.setObjectName("lineEdit_StudentName")
        self.DataInput.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_StudentName)
        self.label_StudentNumber = QtWidgets.QLabel(parent=NewUserData)
        self.label_StudentNumber.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_StudentNumber.setObjectName("label_StudentNumber")
        self.DataInput.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_StudentNumber)
        self.lineEdit_StudentNumber = QtWidgets.QLineEdit(parent=NewUserData)
        self.lineEdit_StudentNumber.setStyleSheet("background-color: rgb(246, 245, 244);")
        self.lineEdit_StudentNumber.setObjectName("lineEdit_StudentNumber")
        self.DataInput.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_StudentNumber)
        self.label_CourseOfStudy = QtWidgets.QLabel(parent=NewUserData)
        self.label_CourseOfStudy.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_CourseOfStudy.setObjectName("label_CourseOfStudy")
        self.DataInput.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_CourseOfStudy)
        self.comboBox_CourseOfStudy = QtWidgets.QComboBox(parent=NewUserData)
        self.comboBox_CourseOfStudy.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.comboBox_CourseOfStudy.setObjectName("comboBox_CourseOfStudy")
        self.DataInput.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox_CourseOfStudy)
        self.verticalLayout.addLayout(self.DataInput)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=NewUserData)
        self.buttonBox.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.retranslateUi(NewUserData)
        QtCore.QMetaObject.connectSlotsByName(NewUserData)

    def retranslateUi(self, NewUserData):
        _translate = QtCore.QCoreApplication.translate
        NewUserData.setWindowTitle(_translate("NewUserData", "Add User Data"))
        self.label_University.setText(_translate("NewUserData", "University"))
        self.label_StudentName.setText(_translate("NewUserData", "Name"))
        self.lineEdit_StudentName.setPlaceholderText(_translate("NewUserData", "First Name Last Name"))
        self.label_StudentNumber.setText(_translate("NewUserData", "Student-Number"))
        self.label_CourseOfStudy.setText(_translate("NewUserData", "Course of Study"))
