# Form implementation generated from reading ui file 'widget_addgrade.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddGrade(object):
    def setupUi(self, AddGrade):
        AddGrade.setObjectName("AddGrade")
        AddGrade.resize(396, 180)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddGrade.sizePolicy().hasHeightForWidth())
        AddGrade.setSizePolicy(sizePolicy)
        AddGrade.setMinimumSize(QtCore.QSize(233, 180))
        AddGrade.setMaximumSize(QtCore.QSize(405, 180))
        AddGrade.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(AddGrade)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=AddGrade)
        self.frame_2.setStyleSheet("background-color: rgb(6, 12, 10);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Modul = QtWidgets.QLabel(parent=self.frame_2)
        self.label_Modul.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_Modul.setObjectName("label_Modul")
        self.verticalLayout.addWidget(self.label_Modul)
        self.label_Passed = QtWidgets.QLabel(parent=self.frame_2)
        self.label_Passed.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_Passed.setObjectName("label_Passed")
        self.verticalLayout.addWidget(self.label_Passed)
        self.label_Grade = QtWidgets.QLabel(parent=self.frame_2)
        self.label_Grade.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_Grade.setObjectName("label_Grade")
        self.verticalLayout.addWidget(self.label_Grade)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(parent=AddGrade)
        self.frame.setStyleSheet("background-color: rgb(6, 12, 10);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_Modul = QtWidgets.QComboBox(parent=self.frame)
        self.comboBox_Modul.setStyleSheet("background-color: rgb(192, 191, 188);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_Modul.setObjectName("comboBox_Modul")
        self.verticalLayout_2.addWidget(self.comboBox_Modul)
        self.comboBox_Passed = QtWidgets.QComboBox(parent=self.frame)
        self.comboBox_Passed.setStyleSheet("background-color: rgb(192, 191, 188);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_Passed.setObjectName("comboBox_Passed")
        self.verticalLayout_2.addWidget(self.comboBox_Passed)
        self.lineEdit_Grade = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_Grade.setStyleSheet("background-color: rgb(246, 245, 244);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_Grade.setObjectName("lineEdit_Grade")
        self.verticalLayout_2.addWidget(self.lineEdit_Grade)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AddGrade)
        self.buttonBox.setStyleSheet("background-color: rgb(246, 245, 244);\n"
"color: rgb(0, 0, 0);")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(AddGrade)
        QtCore.QMetaObject.connectSlotsByName(AddGrade)

    def retranslateUi(self, AddGrade):
        _translate = QtCore.QCoreApplication.translate
        AddGrade.setWindowTitle(_translate("AddGrade", "Add Grade"))
        self.label_Modul.setText(_translate("AddGrade", "Modul"))
        self.label_Passed.setText(_translate("AddGrade", "Passed"))
        self.label_Grade.setText(_translate("AddGrade", "Grade"))
