# Form implementation generated from reading ui file 'widget_addcourse.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddCourse(object):
    def setupUi(self, AddCourse):
        AddCourse.setObjectName("AddCourse")
        AddCourse.resize(405, 180)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddCourse.sizePolicy().hasHeightForWidth())
        AddCourse.setSizePolicy(sizePolicy)
        AddCourse.setMinimumSize(QtCore.QSize(307, 148))
        AddCourse.setMaximumSize(QtCore.QSize(405, 180))
        AddCourse.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(AddCourse)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_labels = QtWidgets.QWidget(parent=AddCourse)
        self.widget_labels.setStyleSheet("background-color: rgb(6, 12, 10);")
        self.widget_labels.setObjectName("widget_labels")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_labels)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_CourseName = QtWidgets.QLabel(parent=self.widget_labels)
        self.label_CourseName.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_CourseName.setObjectName("label_CourseName")
        self.verticalLayout.addWidget(self.label_CourseName)
        self.label_ECTSPoints = QtWidgets.QLabel(parent=self.widget_labels)
        self.label_ECTSPoints.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_ECTSPoints.setObjectName("label_ECTSPoints")
        self.verticalLayout.addWidget(self.label_ECTSPoints)
        self.label_ExamType = QtWidgets.QLabel(parent=self.widget_labels)
        self.label_ExamType.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_ExamType.setObjectName("label_ExamType")
        self.verticalLayout.addWidget(self.label_ExamType)
        self.horizontalLayout.addWidget(self.widget_labels)
        self.frame_inputs = QtWidgets.QFrame(parent=AddCourse)
        self.frame_inputs.setStyleSheet("background-color: rgb(6, 12, 10);")
        self.frame_inputs.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_inputs.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_inputs.setObjectName("frame_inputs")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_inputs)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_CourseName = QtWidgets.QComboBox(parent=self.frame_inputs)
        self.comboBox_CourseName.setStyleSheet("background-color: rgb(192, 191, 188);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_CourseName.setObjectName("comboBox_CourseName")
        self.verticalLayout_2.addWidget(self.comboBox_CourseName)
        self.lineEdit_ECTSPoints = QtWidgets.QLineEdit(parent=self.frame_inputs)
        self.lineEdit_ECTSPoints.setStyleSheet("background-color: rgb(246, 245, 244);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_ECTSPoints.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_ECTSPoints.setObjectName("lineEdit_ECTSPoints")
        self.verticalLayout_2.addWidget(self.lineEdit_ECTSPoints)
        self.comboBox_ExamType = QtWidgets.QComboBox(parent=self.frame_inputs)
        self.comboBox_ExamType.setStyleSheet("background-color: rgb(192, 191, 188);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_ExamType.setObjectName("comboBox_ExamType")
        self.verticalLayout_2.addWidget(self.comboBox_ExamType)
        self.horizontalLayout.addWidget(self.frame_inputs)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AddCourse)
        self.buttonBox.setStyleSheet("background-color: rgb(246, 245, 244);\n"
"color: rgb(0, 0, 0);")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.retranslateUi(AddCourse)
        QtCore.QMetaObject.connectSlotsByName(AddCourse)

    def retranslateUi(self, AddCourse):
        _translate = QtCore.QCoreApplication.translate
        AddCourse.setWindowTitle(_translate("AddCourse", "Add Course"))
        self.label_CourseName.setToolTip(_translate("AddCourse", "<html><head/><body><p><br/></p></body></html>"))
        self.label_CourseName.setText(_translate("AddCourse", "Course Name"))
        self.label_ECTSPoints.setText(_translate("AddCourse", "ECTS Points"))
        self.label_ExamType.setToolTip(_translate("AddCourse", "<html><head/><body><p><br/></p></body></html>"))
        self.label_ExamType.setText(_translate("AddCourse", "Exam Type"))
        self.lineEdit_ECTSPoints.setText(_translate("AddCourse", "5"))
        self.lineEdit_ECTSPoints.setPlaceholderText(_translate("AddCourse", "5"))
