# Form implementation generated from reading ui file 'widget_adduserdata.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NewUserData(object):
    def setupUi(self, NewUserData):
        NewUserData.setObjectName("NewUserData")
        NewUserData.resize(405, 180)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NewUserData.sizePolicy().hasHeightForWidth())
        NewUserData.setSizePolicy(sizePolicy)
        NewUserData.setMinimumSize(QtCore.QSize(405, 180))
        NewUserData.setMaximumSize(QtCore.QSize(405, 180))
        NewUserData.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        NewUserData.setWindowOpacity(1.0)
        NewUserData.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(NewUserData)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=NewUserData)
        self.frame_2.setStyleSheet("background-color: rgb(6, 12, 10);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_University = QtWidgets.QLabel(parent=self.frame_2)
        self.label_University.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_University.setObjectName("label_University")
        self.verticalLayout_2.addWidget(self.label_University)
        self.label_StudentName = QtWidgets.QLabel(parent=self.frame_2)
        self.label_StudentName.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_StudentName.setObjectName("label_StudentName")
        self.verticalLayout_2.addWidget(self.label_StudentName)
        self.label_StudentNumber = QtWidgets.QLabel(parent=self.frame_2)
        self.label_StudentNumber.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_StudentNumber.setObjectName("label_StudentNumber")
        self.verticalLayout_2.addWidget(self.label_StudentNumber)
        self.label_CourseOfStudy = QtWidgets.QLabel(parent=self.frame_2)
        self.label_CourseOfStudy.setStyleSheet("font: 700 11pt \"Graduate\" ;\n"
"color: rgb(255, 255, 255);")
        self.label_CourseOfStudy.setObjectName("label_CourseOfStudy")
        self.verticalLayout_2.addWidget(self.label_CourseOfStudy)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(parent=NewUserData)
        self.frame.setStyleSheet("background-color: rgb(6, 12, 10);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_University = QtWidgets.QComboBox(parent=self.frame)
        self.comboBox_University.setStyleSheet("background-color: rgb(192, 191, 188);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_University.setObjectName("comboBox_University")
        self.verticalLayout.addWidget(self.comboBox_University)
        self.lineEdit_StudentName = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_StudentName.setStyleSheet("background-color: rgb(246, 245, 244);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_StudentName.setText("")
        self.lineEdit_StudentName.setObjectName("lineEdit_StudentName")
        self.verticalLayout.addWidget(self.lineEdit_StudentName)
        self.lineEdit_StudentNumber = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_StudentNumber.setStyleSheet("background-color: rgb(246, 245, 244);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_StudentNumber.setObjectName("lineEdit_StudentNumber")
        self.verticalLayout.addWidget(self.lineEdit_StudentNumber)
        self.comboBox_CourseOfStudy = QtWidgets.QComboBox(parent=self.frame)
        self.comboBox_CourseOfStudy.setStyleSheet("background-color: rgb(192, 191, 188);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_CourseOfStudy.setObjectName("comboBox_CourseOfStudy")
        self.verticalLayout.addWidget(self.comboBox_CourseOfStudy)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=NewUserData)
        self.buttonBox.setStyleSheet("background-color: rgb(246, 245, 244);\n"
"color: rgb(0, 0, 0);")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(NewUserData)
        QtCore.QMetaObject.connectSlotsByName(NewUserData)

    def retranslateUi(self, NewUserData):
        _translate = QtCore.QCoreApplication.translate
        NewUserData.setWindowTitle(_translate("NewUserData", "Add User Data"))
        self.label_University.setText(_translate("NewUserData", "University"))
        self.label_StudentName.setText(_translate("NewUserData", "Student Name"))
        self.label_StudentNumber.setText(_translate("NewUserData", "Student Number"))
        self.label_CourseOfStudy.setText(_translate("NewUserData", "Course of Study"))
        self.lineEdit_StudentName.setPlaceholderText(_translate("NewUserData", "First Name Last Name"))
